### ISSUE TITLE
Stuck task - syncMembers

### ISSUE THREAD

**Issue by itsAliAvali** [ABSAhmad/IpsDiscordIntegration#24]
task appears to be locking often making the prompt appear ; cron is setup correctly, even tried with a web cron as well. manually running the task appears to go through successfully, but will then produce the imaged prompt again after a few days since it runs daily.
![image](https://user-images.githubusercontent.com/2025022/29159564-a3c08ff4-7d74-11e7-8ee5-b7c9dbea00d2.png)
![image](https://user-images.githubusercontent.com/2025022/29159600-c149c450-7d74-11e7-87cd-7701c5a7332a.png)

**Comment by ABSAhmad** [comment]
Can you please take a look in your system/error logs for more clues?

**Comment by itsAliAvali** [comment]
php is allowed to use cron, and cron is up to date ;

IPS\Http\Request\CurlException::28
Operation timed out after 10000 milliseconds with 0 out of 0 bytes received

Backtrace:
```
#0 ..\system\Http\Request\Curl.php(402): IPS\Http\Request\_Curl->_execute()

#1 ..\system\Http\Request\Curl.php(278): IPS\Http\Request\_Curl->_executeAndFollowRedirects('GET', NULL)

#2 ..\applications\discord\sources\Api\Api.php(248): IPS\Http\Request\_Curl->get()

#3 ..\applications\discord\sources\Api\AbstractResponse.php(55): IPS\discord\_Api->send()

#4 ..\applications\discord\sources\Api\Member.php(27): IPS\discord\Api\_AbstractResponse->handleApi()

#5 ..\applications\core\sources\ProfileSync\Discord.php(157): IPS\discord\Api\_Member->getDiscordUser('l5zbfgg0OruZB83...')

#6 ..\applications\core\sources\ProfileSync\Discord.php(58): IPS\core\ProfileSync\_Discord->get()

#7 ..\applications\core\sources\ProfileSync\Discord.php(106): IPS\core\ProfileSync\_Discord->user()

#8 ..\applications\core\sources\ProfileSync\ProfileSyncAbstract.php(243): IPS\core\ProfileSync\_Discord->photo()

#9 ..\applications\core\tasks\profilesync.php(48): IPS\core\ProfileSync\_ProfileSyncAbstract->sync()

#10 ..\system\Task\Task.php(248): IPS\core\tasks\_profilesync->execute()

#11 ..\system\Task\Task.php(217): IPS\_Task->run()

#12 ..\applications\core\interface\task\task.php(60): IPS\_Task->runAndLog()

#13 {main}
```

**Comment by ABSAhmad** [comment]
This should be fixed with the new tasks
