### ISSUE TITLE
Bot tries to set nickname of Discord owner when "Sync Names" is on

### ISSUE THREAD

**Issue by duilio1337** [ABSAhmad/IpsDiscordIntegration#30]
I was having a problem getting to my account setting on my website and it was throwing errors. I read into the logs and determined that it was caused by the bot trying to set my nickname on Discord which it did not have permissions for since I am the creator of the Discord and administrators apparently can't change the nicknames of the creator.

```array (
  'code' => 0,
  'message' => 'Privilege is too low...',
)

#0 C:\inetpub\wwwroot\hyped-gamingcom\applications\discord\sources\Api\AbstractResponse.php(68): IPS\_Log::log('array (\n  'code...', 'discord_excepti...')
#1 C:\inetpub\wwwroot\hyped-gamingcom\applications\discord\sources\Api\GuildMember.php(57): IPS\discord\Api\_AbstractResponse->handleApi()
#2 C:\inetpub\wwwroot\hyped-gamingcom\applications\core\sources\ProfileSync\Discord.php(63): IPS\discord\Api\_GuildMember->update(Object(IPS\Member))
#3 C:\inetpub\wwwroot\hyped-gamingcom\applications\core\sources\ProfileSync\Discord.php(128): IPS\core\ProfileSync\_Discord->user()
#4 C:\inetpub\wwwroot\hyped-gamingcom\system\Theme\Theme.php(824) : eval()'d code(7536): IPS\core\ProfileSync\_Discord->name()
#5 C:\inetpub\wwwroot\hyped-gamingcom\system\Theme\SandboxedTemplate.php(56): IPS\Theme\class_core_front_system->settingsOverview(Array, NULL)
#6 C:\inetpub\wwwroot\hyped-gamingcom\applications\core\modules\front\system\settings.php(160): IPS\Theme\_SandboxedTemplate->__call('settingsOvervie...', Array)
#7 [internal function]: IPS\core\modules\front\system\_settings->_overview()
#8 C:\inetpub\wwwroot\hyped-gamingcom\applications\core\modules\front\system\settings.php(54): call_user_func(Array)
#9 C:\inetpub\wwwroot\hyped-gamingcom\system\Dispatcher\Controller.php(96): IPS\core\modules\front\system\_settings->manage()
#10 C:\inetpub\wwwroot\hyped-gamingcom\applications\core\modules\front\system\settings.php(34): IPS\Dispatcher\_Controller->execute()
#11 C:\inetpub\wwwroot\hyped-gamingcom\system\Dispatcher\Dispatcher.php(146): IPS\core\modules\front\system\_settings->execute()
#12 C:\inetpub\wwwroot\hyped-gamingcom\index.php(12): IPS\_Dispatcher->run()
#13 {main}

**Comment by itsAliAvali** [comment]
is the bot's role above your role? and have the administrator flag on it?
![image](https://user-images.githubusercontent.com/2025022/31361299-5994fd7e-ad18-11e7-9ce6-b6764f5242f0.png)

**Comment by duilio1337** [comment]
Yes. My only rank is Owner.
![screenshot_1](https://user-images.githubusercontent.com/5445941/31362212-2b2ff0da-ad0c-11e7-87f5-5f0356cb6363.png)

**Comment by duilio1337** [comment]
I had a friend give me administrator on his Discord and I was unable to change his nickname as he is the owner.

**Comment by ABSAhmad** [comment]
This will be fixed with the new update
