### ISSUE TITLE
[2.0.0 Alpha1] When attempting to edit group

### ISSUE THREAD

**Issue by itsAliAvali** [ABSAhmad/IpsDiscordIntegration#35]
`Error: Call to undefined method IPS\discord\Api\Guild::i() (0)
#0www\applications\core\modules\admin\members\groups.php(202): IPS\discord\extensions\core\GroupForm\_ExtendWithDiscordRoles->process(Object(IPS\Helpers\Form), Object(IPS\Member\Group))
#1 www\system\Dispatcher\Controller.php(85): IPS\core\modules\admin\members\_groups->form()
#2 www\applications\core\modules\admin\members\groups.php(34): IPS\Dispatcher\_Controller->execute()
#3 www\system\Dispatcher\Dispatcher.php(146): IPS\core\modules\admin\members\_groups->execute()
#4 www\admin\index.php(14): IPS\_Dispatcher->run()
#5 {main}`

**Comment by ABSAhmad** [comment]
Weird, should be there. Can you check if the file exists on your server `discord/sources/Api/Guild/Guild.php` please?

**Comment by itsAliAvali** [comment]
www\applications\discord\sources\Api\Guild\Guild.php exists. zip'd since github doesnt let me direct upload a php file lol
[Guild.zip](https://github.com/ABSAhmad/IpsDiscordIntegration/files/2364716/Guild.zip)

**Comment by itsAliAvali** [comment]
![image](https://user-images.githubusercontent.com/2025022/45269434-e90c9000-b453-11e8-81ec-4c0bba716c59.png)
noticed file structure is a little different... pre-2.0 files not good anymore?
