### ISSUE TITLE
API Exception ForbiddenException

### ISSUE THREAD

**Issue by andriihorpenko** [ABSAhmad/IpsDiscordIntegration#5]
Hello. I found huge issue(maybe). So after I synced my account to discord everything is normal. But if I change role throw discord or forum, I lose access to Profile Settings page. Here is error:

Reinstalled few times, but unsuccessfully.. 

IPS\discord\Api\Exception\ForbiddenException:  (0)
#0 /storage/h3/752/781752/public_html/forum/applications/discord/sources/Api/AbstractResponse.php(63): IPS\discord\Api\_AbstractResponse->throwException('403')
#1 /storage/h3/752/781752/public_html/forum/applications/discord/sources/Api/GuildMember.php(50): IPS\discord\Api\_AbstractResponse->handleApi()
#2 /storage/h3/752/781752/public_html/forum/applications/core/sources/ProfileSync/Discord.php(63): IPS\discord\Api\_GuildMember->updateRoles(Object(IPS\Member))
#3 /storage/h3/752/781752/public_html/forum/applications/core/sources/ProfileSync/Discord.php(129): IPS\core\ProfileSync\_Discord->user()
#4 /storage/h3/752/781752/public_html/forum/system/Theme/Theme.php(757) : eval()'d code(6891): IPS\core\ProfileSync\_Discord->name()
#5 [internal function]: IPS\Theme\class_core_front_system->settingsOverview(Array)
#6 /storage/h3/752/781752/public_html/forum/system/Theme/SandboxedTemplate.php(57): call_user_func_array(Array, Array)
#7 /storage/h3/752/781752/public_html/forum/applications/core/modules/front/system/settings.php(148): IPS\Theme\_SandboxedTemplate->__call('settingsOvervie...', Array)
#8 [internal function]: IPS\core\modules\front\system\_settings->_overview()
#9 /storage/h3/752/781752/public_html/forum/applications/core/modules/front/system/settings.php(55): call_user_func(Array)
#10 /storage/h3/752/781752/public_html/forum/system/Dispatcher/Controller.php(96): IPS\core\modules\front\system\_settings->manage()
#11 /storage/h3/752/781752/public_html/forum/applications/core/modules/front/system/settings.php(35): IPS\Dispatcher\_Controller->execute()
#12 /storage/h3/752/781752/public_html/forum/system/Dispatcher/Dispatcher.php(129): IPS\core\modules\front\system\_settings->execute()
#13 /storage/h3/752/781752/public_html/forum/index.php(13): IPS\_Dispatcher->run()
#14 {main}

**Comment by andriihorpenko** [comment]
It crashes only for Moderators and Administrators groups.

**Comment by andriihorpenko** [comment]
Sorry for that.. My bot has to have Admin permissions..
